project_name: waterflow

__base__:
  - config/waterflow_352x352.yaml

diffusion_model:
  name: waterflow.RectifiedFlowWrapper.CondRectifiedFlow
  params:
    model: #model
    image_size: 384
    channels: 1
    cond_channels: 3
    loss_type: 'waterflow.loss.structure_loss'
    num_sample_steps: 20
    solver_method: "euler"
    pred_objective: "x0"

    predict: "flow"
    clip_values: [-1.0, 1.0]
    odeint_kwargs:
      atol: 1e-5
      rtol: 1e-5
      method: "euler"
    path_type: "cond_ot"
    sigma_min: 1e-5
    clip_sample_denoised: True

# 训练数据集
train_dataset:
  name: dataset.underwater_data.UnderwaterPolypObjDataset
  params:
    image_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD10K/TrainDataset/Imgs/'
    gt_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD10K/TrainDataset/GT/'
    trainsize: 384
    boundary_modification: True
    use_depth: True                    # 训练时使用深度图
    depth_estimation_method: "midas"   # 深度估计方法
    depth_root: "/root/autodl-tmp/WaterFlow/media/dataset/USOD10K/TrainDataset/DepRaw/"  # 如果有预计算的深度图

test_dataset:
  USOD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD10K/TestDataset/Imgs/'
      gt_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD10K/TestDataset/GT/'
      testsize: 384
  UFO120:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/root/autodl-tmp/WaterFlow/media/dataset/UFO120/TestDataset/Imgs/'
      gt_root: '/root/autodl-tmp/WaterFlow/media/dataset/UFO120/TestDataset/GT/'
      testsize: 384
  SUIM:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/root/autodl-tmp/WaterFlow/media/dataset/SUIM/TestDataset/Imgs/'
      gt_root: '/root/autodl-tmp/WaterFlow/media/dataset/SUIM/TestDataset/GT/'
      testsize: 384
  USOD:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD/TestDataset/Imgs/'
      gt_root: '/root/autodl-tmp/WaterFlow/media/dataset/USOD/TestDataset/GT/'
      testsize: 384